### ISSUE TITLE
Mulighed for at vælge alle i blanket og indsendelsesoversigter

### ISSUE THREAD

**Issue by blanketmotor** [blanketmotor/blanketmotor#17]
**User story**
Som myndighedsbruger vil jeg gerne kunne vælge alle elementer i en visning for ikke at skulle markere dem alle enkeltvis.

**Beskrivelse**
På både oversigten over blanketter og oversigten over indsendelser er det i dag muligt at markere enkelte blanketter til forskellige operationer, men der mangler muligheden for at kunne markere eller afmarkere alle på én gang, hvilket er en oplagt quality-of-life ændring.

**Acceptkriterier**
1. På oversigten over designede blanketter skal det være muligt at
   1. markere alle rækker i en given visning
   2. fjerne markering af alle rækker i en given visning
2. På oversigten over indsendte blanketter skal det være muligt at
   1. markere alle rækker i en given visning
   2. fjerne markering af alle rækker i en given visning

**Comment by HeleneATP** [comment]
Det vil have stor værdi for ATP :-)
