### ISSUE TITLE
Validering af udenlandske adresser

### ISSUE THREAD

**Issue by blanketmotor** [blanketmotor/blanketmotor#2]
**User story**
Som blanketdesigner vil jeg gerne kunne lave valideringer af udenlandske adresser for at sikre en højere datakvalitet af indberettet data

**Beskrivelse**
Formålet med denne story er at lave en udenlandsk udgave af det allerede eksisterende adresseopslag, så der også er mulighed for at kunne lave valideringer af udenlandske adresser, hvis der er behov for den slags i blanketter.

**Acceptkriterier**
1. Det skal være muligt at validere en indtastet udenlandsk adresse
2. Valideringen skal udstilles som en del af Blanketmotorens servicelag

**Afklaringer**
1. Skal vi kunne udstille forskellige grader af validering og ikke kun Ja/Nej

**Comment by blanketmotor** [comment]
Intern sag: [BMTO-3242](https://jira.erst.dk/browse/BMTO-3242)

**Comment by nvp-nc** [comment]
Denne funktionalitet er lagt i produktion i forbindelse med [Release 3.9.0](https://blanketmotor.atlassian.net/wiki/spaces/BW/blog/2024/08/27/416022589/Release+3.9.0).
Nærmere information kan findes under https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/5308417/Udstillede+services#Validering-af-udenlandske-adresser.
