### ISSUE TITLE
Udvid betalingsmodul med konto til konto betalinger

### ISSUE THREAD

**Issue by blanketmotor** [blanketmotor/blanketmotor#20]
**User story**
Som anmelder vil jeg gerne kunne foretage større betalinger som konto til konto frem for at skulle bruge mine betalingskort.

**Beskrivelse**
Ved større betalinger i Blanketmotorens betalingsmodul kan de nuværende muligheder med betalingskort og MobilePay godt komme til at føles voldsomme og et supplement med konto til konto betalinger kunne derfor være interessant at kigge på.

Eksempler på udbydere af konto til konto betalinger er eksempelvis MobilePeoples NemBetaling https://mobilepeople.dk/nembetaling/ eller Aiia Pay https://www.aiia.eu/products/aiia-pay 

**Acceptkriterier**

1. Ved brug af betalingsmodulet i Blanketmotoren skal der foruden opkobling på Easy platformen være mulighed for at anvende en platform med konto til konto betalinger.
2. ...

**Comment by JensBoLi** [comment]
Er der noget nyt i forhold til denne sag?

**Comment by blanketmotor** [comment]
Hej @JensBoLi 

Mange tak for din forespørgsel, og vi beklager den sene tilbagemelding. 

Som bekendt ligger Blanketmotorens betalingsløsninger på Easy-platformen. Mens vi relativt let kan tilføje flere løsninger fra Easy til Blanketmotoren, er det desværre ikke helt så let at tilkoble en ekstra udbyder til nuværende setup. Endvidere har foreløbige analyser vist, at opgaven vil være ret omkostningsfuld at gennemføre, og sammenholdt med værdien skabt af konto til konto betalinger har vi besluttet os for at lukke sagen igen uden yderligere handling. 

I fald behovet for konto til konto betalinger senere hen skulle vise sig at vokse, vil vi naturligvis gerne oprette en ny opgave på baggrund heraf. 

Med venlig hilsen

Blanketmotorens Produktteam
