### ISSUE TITLE
Genudsend beskeder fra Blanketmotoren

### ISSUE THREAD

**Issue by blanketmotor** [blanketmotor/blanketmotor#22]
**User story**
Som myndighedsadministrator vil jeg gerne kunne genudsende en besked fra Blanketmotoren så borgeren/virksomheden kan få sine beskeder i tilfælde af udfald på den oprindelige afsendelse

**Beskrivelse**
Der sker fra tid til anden udfald på beskedafsendelser fra Blanketmotoren, hvad end der er tale om fejl på mailserver, hos Digital Post eller noget tredje og der er derfor behov for at kunne genudsende beskeder, hvilket i dag er en langsommelig og manuel proces. Der er derfor et potentiale i at gøre denne funktionalitet tilgængelig for de enkelte myndighedsadministratorer således, at de selv kan styre genudsendelser.

Opgaven er tæt knyttet til #21 som skal give myndighedsadministratorer et overblik over beskedudsendelser

**Acceptkriterier**

1. Som myndighedsadministrator skal jeg kunne genudsende en fejlet besked
    1. Beskeden skal sendes til samme modtager som første gang
    2. Beskeden skal have samme indhold som den oprindelige besked

**Afklaringer**

- ~~Skal man kunne genudsende beskeder der ikke er registreret som fejlede i Blanketmotoren?~~ Ja
- ~~Skal der være nogen begrænsninger for hvilke beskedtyper, der skal kunne genudsendes?~~ Nej

**Comment by kra055** [comment]
For Rigspolitiets vedkommende er svaret til afklaringerne:
- Ja, man skal kunne genudsende beskeder, der ikke er registreret som fejlede
- Nej, der skal ikke være nogen begrænsninger for hvilke beskedtyper, der skal kunne genudsendes

**Comment by blanketmotor** [comment]
Produktionssat med version 3.1.0
