### ISSUE TITLE
Understøttelse af REST endepunkter og JSON

### ISSUE THREAD

**Issue by Solle82** [blanketmotor/blanketmotor#27]
**User story**
Som myndighed vil jeg gerne have mulighed for at modtage indsendelser i JSON format via et RESTFull endepunkt

**Beskrivelse**
Da SOAP er mindre supporteret i Microsoft .NET (efter .Net framework 4.x) kunne det være til gavn at kunne arbejde med REST services for at kunne holde modtagerservices up-to-date.

**Acceptkriterier**
 - Mulighed for at vælge endepunkt som SOAP eller REST
 - Der kan i modtagerenden modtages blanketdata i JSON format

**Comment by Solle82** [comment]
Jeg tænker at JSON formatet kan sagtens bibeholders i samme struktur som jeres SOAP body gør i dag, hvor form-data bibeholdes i XML - Det vil potentielt også kræve færre rettelser hos myndighederne.

Data skal altid sendes med POST da det - inkl. bilag - bliver for mange data (url query længden) via GET.
i REST er PUT og DELETE tiltænkt andre funktioner der ikke vil give mening i denne kontekst.

**Comment by blanketmotor** [comment]
Hej

Den er ikke på vores road map lige nu

**Comment by blanketmotor** [comment]
Hej @Solle82 og @TheutMeier

Pågældende opgave er udviklet og blev lagt i produktion d. 9. april 2024 i forbindelse med [Release 3.5.0](https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/80281601/Release+notes). 

Vi lukker derfor denne sag i Github igen. 

Med venlig hilsen 

Blanketmotorens Produktteam
