### ISSUE TITLE
Tilføj CVR-nummer på virksomheden i e-mail med titlen "blanket er klar til underskrift"

### ISSUE THREAD

**Issue by ANBRU-DIGST** [blanketmotor/blanketmotor#35]
**User story**
Som tegningsberettiget/administrator i flere virksomheder, som benytter blanketmotoren, vil jeg gerne have at CVR-nummeret fremgår af e-mailen "blanket er klar til underskrift" for at jeg kan se hvilken signatur jeg skal anvende til underskriften.

**Beskrivelse**
Jeg sidder i Digital Post, hvor vi anvender blanketmotoren til oprettelse af første "brugerrettighedsadministrator" i en række virksomheder. I den forbindelse er vi blevet kontaktet af en bruger som repræsenterer en lang række virksomheder, og derfor også har modtaget en tilsvarende lang række e-mails omkring underskrivelse af blanketterne. I den forbindelse efterlyser brugeren at det tydeligt fremgår af e-mail hvilken organisation den pågælden blanket/underskrift omhandler.

**Acceptkriterier**
CVR-nummer på den relevante organisation fremgår af e-mailen "blanket er klar til underskrift"

**Evt. ønsket releasedato / deadline**
Ingen deadline, blot et ønske :)

**Comment by ANBRU-DIGST** [comment]
![Uden titel](https://github.com/blanketmotor/blanketmotor/assets/132064801/3be6bae2-4ad1-4dc3-848b-06425ec6b671)

**Comment by blanketmotor** [comment]
Hej

Vi introducerede sidste forår en ny udgave af medsigneringskomponenten, hvor vi man kan koble den direkte op på et CVR-nummer i stedet for en e-mail adresser. Så sendes anmodningen til det valgte CVR-nummers digitale postkasse https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/34996225/Inds+ttelse+af+medsigneringskomponenten

Alternativt har vi en mere avanceret udgave af medsigneringskomponenten, der er bundet op på virksomhedernes reelle tegningsregel https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/30572545/Tegningsregel

**Comment by blanketmotor** [comment]
Hej @ANBRU-DIGST 

Denne opgave blev udviklet under Github #38 og deployet til produktion i forbindelse med [Release 3.5.0](https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/80281601/Release+notes) d. 9, april 2024.

Vi lukker derfor sagen her i Github igen.

Med venlig hilsen

Blanketmotorens Produktteam
