### ISSUE TITLE
Mulighed for at hente oplysninger vedr. pligter og forretningsområder mv. i Erhvervssystemet

### ISSUE THREAD

**Issue by JoanAndersen** [blanketmotor/blanketmotor#36]
Formål: at kunne gøre brug af virksomhedens registreringer (pligter, forretningsområder mv) i forbindelse med udfyldelse af digitale blanketter. Oplysninger ligger samme sted som SE-numrene

Eksempler:
•	Virksomheden beder om en registrering for batterier – det er muligt at tjekke om virksomheden er registreret allerede. 
•	En virksomhed beder om en registrering som kræver at virksomheden er registreret for moms. Der tjekkes om virksomheden allerede er registreret – hvis ikke gøres de opmærksom på at virksomheden først kan få pligten når registrering for moms er gennemført
•	En virksomhed bestiller stempelmærker til pibetobak – der foretages et tjek om virksomheden er registreret for tobak
•	En virksomhed beder om fremrykket tilbagebetaling af energiafgift -der foretages et tjek om virksomheden er registreret for forholdet.

Vi er bevidste om at blanketten ikke forholder sig til ”ikke-behandlede” sager på sagslisten. 

Krav:
-	Blanketten skal kunne håndtere både opslag på se-nummer og cvr-nummer
-	På baggrund af et se-nummer/cvr-nummer skal det være muligt at finde hvilke pligter virksomheden er registreret for (aktive forhold)
-	På baggrund af et se-nummer/cvr-nummer skal det være muligt at finde hvilke forretningsområde virksomheden er registreret for. 
-	Hvis der foretages et opslag på et se-nummer, skal det være muligt at trække den tilhørende cvr-nummer
-	Det skal alene være de aktive pligter/forretningsområdet som indgår i svaret. 
-	På sigt skal det være muligt at udsøge virksomhedens sikkerhedsstillelser 

Selve opslaget skal ikke være frit tilgængeligt for alle myndighederne som anvender Blanketmotoren. Der skal være krav om, at der indgås en databehandleraftale med Skattestyrelsen før oplysningerne kan anvendes (Tilsvarende adgangen til DMR). 

Der har været afholdt opstartsmøde med Andreas Midfjord den 17 maj 2023.
**Evt. ønsket releasedato / deadline**
DD-MM-ÅÅÅÅ

**Comment by blanketmotor** [comment]
Intern sag: [BMTO-3906](https://jira.erst.dk/browse/BMTO-3906)

**Comment by blanketmotor** [comment]
Lukkes efter aftale.
