### ISSUE TITLE
Mulighed for Trustly ved Nets checkout (bank to bank)

### ISSUE THREAD

**Issue by sisva1** [blanketmotor/blanketmotor#37]
**User story**
Hej Blanketmotor product team!
Som medarbejder i en offentlig Administration vil jeg kunne spare en masse timer ved at have mulighed for at man kan betale via Trustly.

**Beskrivelse**
Muligheden for at kunne betale med Trustly handler først og fremmest om aktivering gennem sin aftale ved Nets.
Dernæst blev der fundet frem til at blanketmotor mangler "consumer" objektet for at kunne vise Trustly som en betalingsmetode.

Blanketmotor request til Nets checkout:
```
"checkout": {
    "charge": false,
    "integrationType": "HostedPaymentPage",
    "returnUrl": "https://blanket.virk.dk/blanketafvikler/public/accepteretBetaling",
    "cancelUrl": "https://blanket.virk.dk/blanketafvikler/public/annullerBetaling?orderid=BLAN-P-AFV-9653179",
    "termsUrl": "https://www.someurl.dk",
    "appearance": {
      "displayOptions": {
        "showOrderSummary": "false"
      }
    },
    "merchantHandlesConsumerData": "true"
  },
```

Styrelsens egen løsning, hvor Trustly er synlig:

```
"checkout": {
    "charge": true,
    "integrationType": "HostedPaymentPage",
    "merchantHandlesConsumerData": true,
    "merchantHandlesShippingCost": false,
    "ReturnUrl": "https://someurl.dk/ordercomplete",
    "termsUrl": "https://someurl.dk/terms",
    "consumerType": null,
    "consumer": {
      "privatePerson": {
        "firstName": "MyFirstName",
        "lastName": "MyLastName"
      },
      "company": null,
      "reference": null,
      "email": "someemail@hotmail.com",
      "shippingAddress": {
        "addressLine1": "Adress 1",
        "addressLine2": "",
        "receiverLine": null,
        "postalCode": "1234",
        "city": "SomeCity",
        "country": "DNK"
      },
      "phoneNumber": {
        "prefix": null,
        "number": null
      }
    }
  },
```
Forskellen er derfor, at betalingerne ikke indeholder et consumer objektet, som er et krav, for at benytte Trustly.
Mere specifikt er det nedenstående, som kræves:
Kravende for brugen af dette er:

- Email
- PrivatePerson
- Company
- ShippingAddress

**Acceptkriterier**
Når Consumer objektet er korrekt implementeret vil Trustly vises i checkout hvis metoden er aktiveret for den individuelle aftale

**Evt. ønsket releasedato / deadline**
Hurtigst muligt :-)

**Comment by nvp-nc** [comment]
Denne funktionalitet er nu lagt i produktion i forbindelse med [Release 3.11.0](https://blanketmotor.atlassian.net/wiki/spaces/BW/blog/2024/12/10/593035276/Release+3.11.0).
Nærmere information kan findes under **Trustly** på https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/16351249/Betaling#Trustly.
