### ISSUE TITLE
Mulighed for at se oplysninger på medunderskriver af blanket

### ISSUE THREAD

**Issue by andrslks** [blanketmotor/blanketmotor#39]
**User story**
En enkel sætning som kort opsummerer, hvilket behov ønsket dækker. Skrives på formen "Som XXX vil jeg gerne YYY for at ZZZ"
Ved indsendelsen af en blanket, som kræver medsignering af anden part, ønsker vi at kunne se oplysninger på medunderskriver. 

**Beskrivelse**
Vi har en række blanketter som udfyldes af en rådgiver, men som skal have tilladelse fra ejer, før end at blanketten kan indsendes. Derfor vil vi gerne kunne se oplysninger på dem som har skrevet blanketten under. På nuværende tidspunkt er det blot muligt at se om blanketten er underskrevet eller ligger og venter på en underskrift før den indsendes.

**Comment by nvp-nc** [comment]
Hej @andrslks 

Menes der på oversigtssiden over indsendte blanketter som dette herunder?
Her vil der også stå, hvis en underskrift er gennemført samt dato og tidspunkt.

![billede](https://github.com/blanketmotor/blanketmotor/assets/142300027/a9003df4-6784-437c-a82e-c0f144e938fc)

**Comment by blanketmotor** [comment]
Hej @andrslks 

Eftersom vi ikke har modtaget svar på vores spørgsmål af 17. januar, ej heller på seneste besked sendt for et par uger siden, lukker vi denne sag igen uden yderligere ageren.

Med venlig hilsen

Blanketmotorens Produktteam
