### ISSUE TITLE
Tilføjelse af flere modtagere af Kvittering

### ISSUE THREAD

**Issue by Tneliis** [blanketmotor/blanketmotor#40]
**User story**
Som bruger vil jeg gerne have mulighed for, at sende kvittering til flere modtagere, for at kunne imødekomme et behov hvor der er flere kontakter som brug for at vide en bestilling er indsendt.

**Beskrivelse**
I vores blanketter oplever vi ofte, at der er flere interessenter som har behov for at vide, at der er indsendt en blanket, og efterfølgende have muligheden for at reagere på denne indsendelse. Eksempelvis vil man have flere brugere som indsender en blanket, hvor det kun er den ene som modtager, selvom alle i princippet har behov for at modtage en kvittering. Ligeledes vil der være eksempel på bestillere, hvor der er behov for at en myndighed eller tilsvarende modtager en kvittering om at der er sket en bestilling på pågældende sag.

**Acceptkriterier**
Mulighed for tilføjelse af flere kvitteringsmodtagere i feltet control-kvittering-email, samt test af at disse modtager en kvitteringsmail.

**Comment by nvp-nc** [comment]
Opgave er oprettet internt ([BMTO-4071](https://jira.erst.dk/browse/BMTO-4071)) og prioriteres ind i den aktive udvikling.

**Comment by nvp-nc** [comment]
Denne funktionalitet er nu lagt i produktion i forbindelse med [Release 3.10.0](https://blanketmotor.atlassian.net/wiki/spaces/BW/blog/2024/10/24/517734402/Release+3.10.0).
Nærmere information kan findes under **Multiple recipients** på https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/16318490/Kvitteringer.
