### ISSUE TITLE
Forslag til ændring i emneteksten i blanket-meddelelser sendt fra Blanketmotor via Digital Post

### ISSUE THREAD

**Issue by ABM123456** [blanketmotor/blanketmotor#41]
Som Blanketmotor administrator vil jeg gerne kunne kontrollere om en specifik blanket indsendt af en specifik bruger er registeret som modtaget i Digital Post loggen.

Modsat ”normale” Digital Post meddelelser, hvor man let kan fremsøge en given meddelelse på CPR eller CVR, er der ikke en let måde at finde en konkret indsendt banket, fordi titlerne er generiske og afsender altid er Erhvervsstyrelsens CVR – 10150817. Dette kunne afhjælpes med en tilføjelse af afsenders CPR / CVR i emnetitlen. Se vedlagte dokument.

[Forslag til ændring i emneteksten i blanket-meddelelser sendt fra Blanketmotor via Digital Post.docx](https://github.com/blanketmotor/blanketmotor/files/14649825/Forslag.til.aendring.i.emneteksten.i.blanket-meddelelser.sendt.fra.Blanketmotor.via.Digital.Post.docx)

**Comment by blanketmotor** [comment]
Intern opgave [BMTO-4082](https://jira.erst.dk/browse/BMTO-4082)

**Comment by blanketmotor** [comment]
Hej @ABM123456  

Mange tak for indsendelsen af dette udviklingsønske, og vi beklager det sene svar. 

I Blanketmotoren eksisterer der allerede en funktionalitet, der sikrer, at man kan skræddersy emne- og beskedkrop for Digital Post endepunkter, ligesom det er tilfældet med e-mail endepunkter. Funktionaliteten er beskrevet nærmere på [Blanketmotor Wiki](https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/28966913/Digital+Post+endepunkt), og ved at anvende denne vil I kunne trække værdien fra de ønskede felter i en hvilken som helst blanket ind i emneteksten. 

Førend vi går i gang med decideret nyudvikling i Blanketmotoren, foreslår vi, at du undersøger, om pågældende funktionalitet vil kunne løse jeres behov eller ej. Når dette er gjort, må du meget gerne vende tilbage, så det bliver klarlagt, om I kan anvende den allerede eksisterende funktionalitet, eller om vi skal gå i gang med noget nytænkning ud fra din beskrivelse. 

Vi ser frem til at høre fra dig. 

Med venlig hilsen

Blanketmotorens Produktteam

**Comment by ABM123456** [comment]
Hej Blanketmotor Produktteam

Tak for svaret. Jeg var faktisk ikke klar over denne mulighed, men jeg har testet den. Den opfylder i delvist vores behov men ikke helt.

{{bm2_blanket_navn}} - navn på blanketten – Blanket ID: {{bm2_indsendt_blanket_id}} - blankettens ID

Ansøgning om Seniorpension - Blanket id: 565593

Jeg har testet denne løsning og den hjælper noget.

MEN vi har en stor udfordring. Blanketmotor anonymiserer forholdsvist hurtigt de indsendte blanketter. Med fare for at vise noget I allerede ved 😊 så ser I her et eksempel på en blanket der er indsendt 30-01-2024 (altså for forholdsvist kort siden).

***@***.***

Det er ret tit at vi får forespørgsler på blanketter der er indsendt for så lang tid siden at blanketten er anonymiseret. Og når først blanketten er anonymiseret, kan vi ikke altid anvende blanket ID,en fordi der kan være tale om en blanket, som vi ikke kan findes internt. Vi har derfor ikke noget at parre blanket ID’en med i vores interne systemer (+det er under alle omstændigheder en tung affære at parre ID’er). Vi har somme tider søgt at tjekke om borgerne har sendt noget ind ved at se om der er sendt en kvittering til vedkommende, men det er kun en indirekte indikation.

Vi vil dog altid kende borgerens navn som det fremgår i CPR registeret og dette navn findes også i Blanketmotor, hvis der er login på blanketten (hvad der næsten altid er). Altså i dette tilfælde testbrugeren ”Telma Kristoffersen”.

***@***.***

Det vi derfor har behov for er at vi kan tilføje dette navn til emnelinjen sammen med Blankt ID’en.

Altså som mock-up ’et her:


{{bm2_blanket_navn}} – Blanket ID: {{bm2_indsendt_blanket_id}}  – Indsendt af:  {{bm2_indsender_navn}}

Ansøgning om Seniorpension - Blanket id: 565593 - Indsendt af: Anders Krabbe Møller

Det burde ikke være et problem at vise disse oplysninger i Digital Post som jo i forvejen gemmer CPR oplysninger og logger alle der anvender løsningen.


Venlig hilsen
Anders Krabbe Møller - ABM
[logo]
Digital Post kanalansvarlig  ·  Channels & Customer Insights
Direkte nummer 22842186  ·  Mobil 22842186
E-mail ***@***.******@***.***>

ATP  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

For information om, hvordan ATP Koncernen behandler dine personoplysninger, se atp.dk/behandling-af-personoplysninger<https://www.atp.dk/behandling-af-personoplysninger>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: blanketmotor ***@***.***>
Sendt: 23. april 2024 11:24
Til: blanketmotor/blanketmotor ***@***.***>
Cc: Anders Krabbe Møller - ABM ***@***.***>; Mention ***@***.***>
Emne: Re: [blanketmotor/blanketmotor] Forslag til ændring i emneteksten i blanket-meddelelser sendt fra Blanketmotor via Digital Post (Issue #41)


Hej @ABM123456<https://github.com/ABM123456>

Mange tak for indsendelsen af dette udviklingsønske, og vi beklager det sene svar.

I Blanketmotoren eksisterer der allerede en funktionalitet, der sikrer, at man kan skræddersy emne- og beskedkrop for Digital Post endepunkter, ligesom det er tilfældet med e-mail endepunkter. Funktionaliteten er beskrevet nærmere på Blanketmotor Wiki<https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/28966913/Digital+Post+endepunkt>, og ved at anvende denne vil I kunne trække værdien fra de ønskede felter i en hvilken som helst blanket ind i emneteksten.

Førend vi går i gang med decideret nyudvikling i Blanketmotoren, foreslår vi, at du undersøger, om pågældende funktionalitet vil kunne løse jeres behov eller ej. Når dette er gjort, må du meget gerne vende tilbage, så det bliver klarlagt, om I kan anvende den allerede eksisterende funktionalitet, eller om vi skal gå i gang med noget nytænkning ud fra din beskrivelse.

Vi ser frem til at høre fra dig.

Med venlig hilsen

Blanketmotorens Produktteam

**Comment by ABM123456** [comment]
Hej Blanketmotor Produktteam

Det forstår jeg selvfølgelig godt. Sådan er det med udvikling. Mange tak for hurtigt svar.

Venlig hilsen
Anders Krabbe Møller - ABM
[logo]
Digital Post kanalansvarlig  ·  Channels & Customer Insights
Direkte nummer 22842186  ·  Mobil 22842186
E-mail ***@***.******@***.***>

ATP  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

For information om, hvordan ATP Koncernen behandler dine personoplysninger, se atp.dk/behandling-af-personoplysninger<https://www.atp.dk/behandling-af-personoplysninger>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: blanketmotor ***@***.***>
Sendt: 24. april 2024 14:08
Til: blanketmotor/blanketmotor ***@***.***>
Cc: Anders Krabbe Møller - ABM ***@***.***>; Mention ***@***.***>
Emne: Re: [blanketmotor/blanketmotor] Forslag til ændring i emneteksten i blanket-meddelelser sendt fra Blanketmotor via Digital Post (Issue #41)


Hej @ABM123456<https://github.com/ABM123456>

Mange tak for dit svar samt for at have undersøgt den funktionalitet med at skræddersy emne- og beskedkrop, der allerede foreligger i Blanketmotoren.

Nu denne ikke kan imødekomme alle jeres ønsker, kigger vi gerne nærmere ind i dine forslag. Vi har dog desværre ikke mulighed for at komme med et bud på, hvornår det bliver, men vi skal nok planlægge det ind så snart der er mulighed herfor, nu vi forstår behovet – og selvfølgelig gerne vil undersøge, hvad der om muligt kan kan gøres.

Vi håber på din forståelse herfor og vender tilbage, når vi har noget nyt.

Med venlig hilsen

Blanketmotorens Produktteam

**Comment by nvp-nc** [comment]
Hej @ABM123456 

Den nuværende funktionalitet understøtter allerede, at man kan hente data fra felter i blanketten, og altså ikke kun de indbyggede værdier som blanketnavn og ID.

Har I fx et felt i blanketten indeholdende navnet (fx `person-navn`), kan det bruges således i både emnefelt og beskedkrop:
`{{//person-navn}}`
Man kan læse nærmere om det her:
https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/21725185/E-mail+endepunkt#XPath-funktionalitet

**Comment by blanketmotor** [comment]
Hej @ABM123456 

I forlængelse af Nicolais besked sendt for godt 3 uger siden, vil vi gerne lige høre, om du har haft mulighed for at kigge nærmere herpå? Og hvis ja så evt. fået afklaret om den eksisterende funktionalitet vil kunne fungere for jer, eller om I fortsat ønsker noget videreudvikling a la den beskrevne tilbage i marts?

På forhånd tak for tilbagemelding 

Blanketmotorens Produktteam

**Comment by ABM123456** [comment]
Hej Produktteam

Beklager at jeg ikke har fået vendt tilbage. Men jeg har testet det og det ser ud som om det faktisk giver den funktionalitet jeg efterlyste. Eneste ulempe er at man skal lave opsætningen manuelt for hver blanket, men det må man jo tage med.

Dette er testen:

Ansøgning om Seniorpension - Blanket id: {{bm2_indsendt_blanket_id}} - Indsendt af: {{//TestNavn}}

Jeg tror at det vil være godt hvis viden om denne mulighed blev formildet fx via en Blanketmotor-CAB eller på den kommende BM Tech-CAB (hvis det passer til konceptet) fordi Digital Post jo i fremtiden bliver en mellemstation i blankettens vej til myndigheden. Derfor er det utroligt værdifuldt at kan identificere den enkelte blanket i Digital Post. Det har faktisk også den ekstra fordel at Digital Post kommer til at blive en form for udvidet log hvor man i flere år – langt længere end i Blanketmotor som jo ret hurtigt anonymiserer – kan finde tidligere indsendte blanketter. Altså under forudsætning af at man laver en opsætning der viser hvem der har sendt blanketten.

Venlig hilsen
Anders Krabbe Møller - ABM
[logo]
Digital Post kanalansvarlig  ·  Channels & Customer Insights
Direkte nummer 22842186  ·  Mobil 22842186
E-mail ***@***.******@***.***>

ATP  ·  Kongens Vænge 8 · 3400 Hillerød
Telefon 70 11 12 13  · www.atp.dk<http://www.atp.dk>  ·  CVR-nr. 43405810
Følg ATP på Facebook<https://www.facebook.com/atpkoncernen> · LinkedIn<https://www.linkedin.com/company/atp>

For information om, hvordan ATP Koncernen behandler dine personoplysninger, se atp.dk/behandling-af-personoplysninger<https://www.atp.dk/behandling-af-personoplysninger>

Oplysningerne i denne e-mail kan være fortrolige og er udelukkende beregnet til brug for de oven for angivne personer eller virksomheder. Vi gør opmærksom på, at udbredelse, omdeling eller kopiering af oplysningerne efter omstændighederne er forbudt. Hvis du har modtaget denne e-mail ved en fejltagelse, bedes du meddele det til afsenderen og derefter slette den. På forhånd tak.



Fra: blanketmotor ***@***.***>
Sendt: 15. maj 2024 13:33
Til: blanketmotor/blanketmotor ***@***.***>
Cc: Anders Krabbe Møller - ABM ***@***.***>; Mention ***@***.***>
Emne: Re: [blanketmotor/blanketmotor] Forslag til ændring i emneteksten i blanket-meddelelser sendt fra Blanketmotor via Digital Post (Issue #41)


Hej @ABM123456<https://github.com/ABM123456>

I forlængelse af Nicolais besked sendt for godt 3 uger siden, vil vi gerne lige høre, om du har haft mulighed for at kigge nærmere herpå? Og hvis ja så evt. fået afklaret om den eksisterende funktionalitet vil kunne fungere for jer, eller om I fortsat ønsker noget videreudvikling a la den beskrevne tilbage i marts?

På forhånd tak for tilbagemelding

Blanketmotorens Produktteam

**Comment by blanketmotor** [comment]
Hej @ABM123456 

Mange tak for din hurtige tilbagemelding samt for at bekræfte, at den eksisterende funktionalitet dækker de behov, du efterlyste – og det selvom opsætningen, som du selv nævner, skal laves manuelt for hver blanket, men det burde kunne sikres relativt hurtigt med copy paste. 

Du har helt ret i, at pågældende mulighed skal formidles ud til alle brugere af Blanketmotor, specielt nu hvor e-mail som endepunkt snart udfases. Hvilket format vi vælger at videreformidle pågældende funktionalitet i, overvejer vi lige internt, men vigtigt er det i alt fald, at det kommer ud til alle.     

Eftersom pågældende funktionalitet dækker dine behov, lukker vi denne sag igen, men takker mange gange for det gode input. 

Med venlig hilsen

Blanketmotorens Produktteam
