### ISSUE TITLE
Større skrift i pdf

### ISSUE THREAD

**Issue by faab-fvst** [blanketmotor/blanketmotor#43]
**Myndighed**
Fødevarestyrelsen

**User story**
Vores sagsbehandlere har ønske om at skriftstørrelsen i den generet pdf bliver større for at det er nemmere at læse for de ansøgninger, der bliver printet ud ved sagsbehandlingen

**Beskrivelse**
Vi har sagsbehandlere, der printer de indkomne henvendelser i forbindelse med sagsbehandlingen. De pointerer, og jeg giver dem ret i, at skriftstørrelsen er relativ lille og svært at læse.

**Acceptkriterier**
Skriften skule gerne svare til mindst størrelse 12

**Comment by blanketmotor** [comment]
Hej @faab-fvst 

Mange tak for din venlige henvendelse. 

Som bekendt er Blanketdesigneren baseret på Orbeon, og den skriftstørrelse, vi opererer med i designeren, er derfor den, der ligger fast i Orbeon. At foretage en generel ændring af skriftstørrelse er ikke en opgave, der umiddelbart lader sig gøre, men dog kan vi informere dig om, at det er muligt at indføre custom styling på blanketter, inklusiv at ændre skriftstørrelse.   

I Blanketmotor Wiki vil du under [PDF Styleguide](https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/2228225/PDF+Styleguide) kunne finde afsnittet ”Skriftstørrelse på diverse tekster”, hvori der angives eksempler på, hvordan man kan ændre skriftstørrelse på blankettitel, brødtekst, control værdier ets. Desuden er der også eksempler på andre custom stylings, som du måske vil finde interessant. 

De forskellige muligheder for custom styling skal naturligvis bruges varsomt og testes grundigt af, men vi håber, du vil kunne bruge eksemplerne som inspiration, nu selve opgaven med at foretage en grundlæggende ændring af Orbeons generelle opsætning ikke er en, vi påtænker at gå i gang med.  

Med venlig hilsen

Blanketmotorens Produktteam
