### ISSUE TITLE
Mulighed for ændring/personalisering af kvitteringstekst (mailbody) i medsignerings kvittering 

### ISSUE THREAD

**Issue by JUSV-FSTYR** [blanketmotor/blanketmotor#45]
Færdselsstyrelsen

Vi har et stort behov for personalisering af de kvitteringer, som senders efter en blanket med medsignering bliver underskrevet af en af parter. 
Vi opliver ofte, at underskriver af blanketten misforstår kvitteringsteksten og tror på, at blanketten er indsendt og under behandling.
Vi synes, at det vil hjælpe vores kunder, at modtage en kvittering, som er komponeret til en bestemt blanket med forklaring at dette kun en underskrift, og blanketten er ikke indsendt, før alle underskrifter er samlet. 

Krav til den nye funktionalitet :  Mulighed for at ændre kvitteringsteksten til medsignerings kvittering, som den findes nu til almindelig afslutningskvittering. 

Venlig hilsen
Julia Svendsen
Færdselsstyrelsen

**Comment by nvp-nc** [comment]
Hej @JUSV-FSTYR 

Er der behov for dynamisk data fra den indsendte blanket, og i så fald hvilke?

/Nicolai

**Comment by nvp-nc** [comment]
Sag oprettet internt: [BMTO-4172](https://jira.erst.dk/browse/BMTO-4172)

**Comment by JUSV-FSTYR** [comment]
Hej Nicolai

I første omgang drejer det sig om at tilpasse selve teksten af kvitteringen. Men hvis man tænker om dynamiske datafletning, kunne det være dejligt at have mulighed at flette informationer om den person, som har underskrevet blanketten, også info om manglende/opfyldte underskrifter.
Men, som jeg siger, fletning er ikke afgørende i den første version af udviklingen af funktionaliteten.

Vh
Julia Svendsen

**Comment by nvp-nc** [comment]
Denne funktionalitet er nu lagt i produktion i forbindelse med [Release 3.11.0](https://blanketmotor.atlassian.net/wiki/spaces/BW/blog/2024/12/10/593035276/Release+3.11.0).
Nærmere information kan findes under https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/591331335/Brugerdefinerede+medsigneringsbeskeder
