### ISSUE TITLE
Digital Post Endepunkt: Mulighed for mere end 10 vedhæftede filer i fremtiden?

### ISSUE THREAD

**Issue by KasperDeylami** [blanketmotor/blanketmotor#47]
Styrelsen for Patientsikkerhed er ved at overgå til Digital Post som endepunkt, hvor vedhæftninger begrænses til 10 vedhæftninger (inkl. pdf og xml-fil) pr. indmeldt blanket.
Bliver begrænsningen på vedhæftede filer fjernet i fremtiden, så man ikke er nødsaget til at flette filerne til en samlet pdf, men kan vedhæfte og fordele det antal vedhæftninger der er behov for til blankettens formål?

**Comment by blanketmotor** [comment]
Hej @KasperDeylami 

Begrænsningen med antallet af vedhæftede filer ligger i Digital Post. 

Vi har tidligere været i dialog med Digitaliseringsstyrelsen omkring denne begrænsning på vedhæftede filer. Det lader ikke til, at den vil blive fjernet, hvorfor det i fremtiden fortsat vil være nødvendigt at flette filer til en samlet PDF på de blanketter, hvor man vurderer, at der er behov herfor. 

Eftersom vi ikke har mulighed for at ændre på nuværende begrænsning fra vores side, lukker vi denne sag igen. 

Med venlig hilsen

Blanketmotorens Produktteam
