### ISSUE TITLE
Få tilsendt kopi af indsendelseskvittering som myndighed

### ISSUE THREAD

**Issue by blanketmotor** [blanketmotor/blanketmotor#9]
**User story**
Som ansvarlig myndighed vil jeg gerne modtage en kopi af anmelders indsendelseskvittering til journalisering på den tilhørende sag

**Beskrivelse**
Jeg kan som sagsbehandlende myndighed have behov for at kunne journalisere anmelders indsendelseskvittering på den tilhørende sag i mit sagsbehandlingssystem og har derfor behov for at modtage en præcis kopi af, hvad anmelder har fået tilsendt.

**Acceptkriterier**

1. Jeg skal som blanketdesigner kunne angive om jeg også vil have tilsendt en kopi af anmelders indsendelseskvittering til blankettens opsatte endepunkt
   1. Det skal KUN være muligt for mail, digital post og SFTP endepunkter
2. Hvis jeg har angivet, at der skal indsendes en kopi af kvitteringen til det opsatte endepunkt, så skal kvitteringen medsendes resten af indsendelsesdata som PDF 
   1. Kvitteringen skal kun sendes til endepunktet, hvis den også er blevet udsendt til anmelders e-mail eller Digitale Post

**Comment by STPSjeto** [comment]
Fra Styrelsen for Patientsikkerheds side, vil vi være taknemmelige for, hvis dette ønske også dækker kvitteringer der er sendt til digital post og at vi som myndighed får en kopi af anmelders kvittering uanset det valgte endepunktstype  for formularen (e-mail, sftp, webservice).

**Comment by blanketmotor** [comment]
Hvis anmelders kvittering sendes til Digital Post, så tænker vi umiddelbart også, at kopien sendes til myndighedens Digitale Post og i så fald anvende et kontaktpunkt på samme vis som Digital Post som endepunkt https://blanketmotor.atlassian.net/wiki/spaces/BW/pages/28966913/Digital+Post+endepunkt?src=search

Hvordan lyder dette?

**Comment by STPSjeto** [comment]
Vi arbejder mod, at vores blanketter som standard altid skal sende en kvittering til borgerens eller virksomhedens digitale post og så skal vi modtage blanketdata, pdf af blanketdata, evt. vedhæftede filer og dertil gerne en kopi af kvittering til anmelder, via webservice. Vi vil gerne anvende webservice så der, via et egenudviklet API på vores side, automatisk oprettes sager i vores ESDH-system, hvor indsendelsen og kvitteringen journaliseres. Da vi ikke kan afvise, at der kan komme til at eksistere blanketter som anvender e-mail eller sftp som endepunkt, evt. midlertidigt i en periode frem til at vi har et API parat til at modtage en nyudviklet blankets data, så foreslår vi, at man som standard inkluderer anmelders kvittering (html/pdf) i den data-pakke der sendes til hver type af endepunkt.

**Comment by blanketmotor** [comment]
Ah ja, det kunne selvfølgelig også hører til under endepunktet som et muligt tilvalg

Vi skal lige kigge på hvor nemt vores nuværende webservice kan udvides med en ekstra fil

**Comment by blanketmotor** [comment]
Det bliver umiddelbart ikke helt nemt at udvide den nuværende webserviceafsendelse med et ekstra dokument, men en mulighed kunne være at kombinere det med en ny webserviceafsendelse fra #27
